@startuml Document_Management_System_UseCase

actor المستخدم
actor المدير
actor النظام

المستخدم --> (تنزيل المستند)
المستخدم --> (طباعة المستند)
المستخدم --> (تسجيل الدخول)
المستخدم --> (التسجيل)

المدير --> (تعيين الأدوار للمستخدمين)
المدير --> (إدارة المستندات)
المدير --> (إدارة الأقسام)
المدير --> (إدارة الخزائن)
المدير --> (إدارة الرفوف)
المدير --> (إدارة الصناديق)
المدير --> (تسجيل الدخول)
المدير --> (التسجيل)

النظام --> (تتبع إجراءات المستند)

المدير --> (عرض المستند)

(تنزيل المستند) .down.> (تتبع إجراءات المستند) : يسجل الإجراء
(طباعة المستند) .down.> (تتبع إجراءات المستند) : يسجل الإجراء

@enduml
